export const stores = [
  {
    storeName: 'Store 1',
    storeAddress: 'Store 1 Address',
    storeContact: 'Store 1 Contact',
    storeEmail: 'Store 1 Email',
    isVerified: false,
    storeCategory: [1, 5],
    storeProducts: [],
  },
  {
    storeName: 'Store 2',
    storeAddress: 'Store 2 Address',
    storeContact: 'Store 2 Contact',
    storeEmail: 'Store 2 Email',
    isVerified: true,
    storeCategory: [3],
    storeProducts: [],
  },
  {
    storeName: 'Store 3',
    storeAddress: 'Store 3 Address',
    storeContact: 'Store 3 Contact',
    storeEmail: 'Store 3 Email',
    isVerified: false,
    storeCategory: [2],
    storeProducts: [],
  },
  {
    storeName: 'Store 4',
    storeAddress: 'Store 4 Address',
    storeContact: 'Store 4 Contact',
    storeEmail: 'Store 4 Email',
    isVerified: false,
    storeCategory: [7],
    storeProducts: [],
  },
  {
    storeName: 'Store 5',
    storeAddress: 'Store 5 Address',
    storeContact: 'Store 5 Contact',
    storeEmail: 'Store 5 Email',
    isVerified: false,
    storeCategory: [6, 8],
    storeProducts: [],
  },
];
